#!/bin/bash
SQL_USER='nhlloserpool'
SQL_PASSWORD='lagisbad'
SQL_HOST='mysql.server'
SQL_PORT='3306'
SQL_DATABASE_NAME='nhlloserpool$nhlloserpool'
SQL_LOG_DATE=$(date +"%F")
OUTPUT_FILE=/home/nhlloserpool/workspace/backups/$SQL_DATABASE_NAME-$SQL_LOG_DATE.sql
mysqldump --host=$SQL_HOST --port=$SQL_PORT --user=$SQL_USER --password=$SQL_PASSWORD $SQL_DATABASE_NAME > $OUTPUT_FILE